config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :products, only: %i[index create]

  root 'products#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :reviews

  validates :url, presence: true, uniqueness: true
  validates :name, :price, presence: true
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
  belongs_to :product
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  expose :products, (-> { Product.all.paginate(page: params[:page]) })
  expose :product

  def index
    respond_to do |format|
      format.html
      format.js {} # TODO: filter functionality
    end
  end

  def create
    build_product
    message = if product.save
                { success: 'Product has been created.' }
              else
                { error: "Can't parse url #{product.url}: #{product.errors.full_messages.join(', ')}" }
              end
    redirect_to root_path, turbolinks: true, flash: message
  end

  private

  def product_params
    params.require(:product).permit(:url, :name, :price)
  end

  def parsed_product
    @product ||= ::WalmartParser.new(product.url)
    @parsed_product ||= @product.parse

    @product
  end

  def build_product
    product.name = parsed_product.name
    product.price = parsed_product.price
    product.reviews.build(parsed_product.reviews.map { |review| { text: review } })
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice' then 'alert alert-dismissable alert-info'
    when 'success' then 'alert alert-dismissable alert-success'
    when 'error' then 'alert alert-dismissable alert-danger'
    when 'alert' then 'alert alert-dismissable alert-danger'
    end
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/layouts/_flash.erb
<% flash.each do |key, value| %>
    <% if value.class == Array %>
        <div class="<%= flash_class(key) %> alert-dismissible fade show" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
            <% value.each do |message| %>
                <%= message %>
                </br>
            <% end %>
        </div>
    <% else %>
        <div class="<%= flash_class(key) %> alert-dismissible fade show" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= value %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_top_navigation.slim
nav.navbar.navbar-toggleable-md.navbar-light.bg-faded.bg-top-navigation

  #navbarTogglerDemo02.collapse.navbar-collapse
    ul.navbar-nav.mr-auto.mt-2.mt-md-0.bt-collapse-padding
      li.nav-item.active.bt-navigation-page
        =<
    .nav-item
      form.search-form action=""
        .form-group.align-items-center.dropdown
          label.sr-only for="search" = t('search')
          input#search.form-control.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" name="search" placeholder = t('placeholders.search') type="text"
          span.fa.fa-search

          .dropdown-menu.dropdown-menu-right.search aria-labelledby="navbarDropdownMenuSearch"
            .results
              h6.dropdown-header
                | Works like a filter

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title WalScrapMart
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'https://use.fontawesome.com/ddd67acb74.js'
  body
    .dashboard
      = render partial: 'layouts/top_navigation'
      #dashboard-main.dashboard-main
        = render partial: 'layouts/flash'
        = yield

app/views/products/_product.slim
li.list-group-item.justify-content-between
  = link_to product.name, product.url, target: '_blank'
  span.badge.badge-default.badge-pill = product.price

app/views/products/create.slim
h1 Products#create
p Find me in app/views/products/create.html.slim

app/views/products/index.slim
= simple_form_for product, url: products_path, method: :post, html: { class: 'form-horizontal' } do |f|
  .row
    .col-9.offset-md-1
      = f.input :url, label: false, placeholder: t('placeholders.url')
    .col-2
      = f.submit '+', class: 'btn bt-btn bt-btn--dark-gray'

h1.page-title = t('.title')
.product-list
  ul.list-group
    = render products

= will_paginate products, renderer: 'BootstrapPaginationHelper::LinkRenderer', previous_label: '&laquo;', next_label: '&raquo;'